plugin_languages: yes

# Analizar todos los repositorios
plugin_languages_indepth: yes

# Mostrar los 8 lenguajes más usados
plugin_languages_limit: 8

# Sección de lenguajes más usados
plugin_languages_sections: most-used

# Solo lenguajes de programación
plugin_languages_categories: programming

# Analizar todos los repositorios públicos
plugin_languages_analysis_timeout: 30
plugin_languages_analysis_timeout_repositories: 100

# No usar actividad reciente
plugin_languages_recent_days: 0
plugin_languages_recent_load: 0

# No ignorar ningún lenguaje
plugin_languages_ignored: ""
